/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.t45k.mockstatic;

import org.apache.commons.lang3.RandomStringUtils;
import org.junit.Test;
import org.mockito.MockedStatic;
import org.mockito.Mockito;

import java.time.LocalDateTime;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void noArgsStaticMethodMockingOk() {
        try (MockedStatic<LocalDateTime> mocked = Mockito.mockStatic(LocalDateTime.class, Mockito.CALLS_REAL_METHODS)) {
            mocked.when(LocalDateTime::now)
                .thenReturn(LocalDateTime.MIN)
                .thenCallRealMethod();

            assertEquals(LocalDateTime.MIN, LocalDateTime.now()); // Passed
            assertNotEquals(LocalDateTime.MIN, LocalDateTime.now()); // Passed
        }
    }

    @Test
    public void onlyPrimitiveTypeArgsStaticMethodMockingOk() {
        try (MockedStatic<LocalDateTime> mocked = Mockito.mockStatic(LocalDateTime.class, Mockito.CALLS_REAL_METHODS)) {
            mocked.when(() -> LocalDateTime.of(2022, 1, 1, 0, 0))
                .thenReturn(LocalDateTime.MIN)
                .thenCallRealMethod();

            assertEquals(LocalDateTime.MIN, LocalDateTime.of(2022, 1, 1, 0, 0)); // Passed
            assertNotEquals(LocalDateTime.MIN, LocalDateTime.of(2022, 1, 1, 0, 0)); // Passed
        }
    }

    @Test
    public void primitiveAndObjectTypeArgsStaticMethodMockingError() {
        try (MockedStatic<RandomStringUtils> mocked = Mockito.mockStatic(RandomStringUtils.class, Mockito.CALLS_REAL_METHODS)) {
            mocked.when(() -> RandomStringUtils.random(1, "ABC"))
                .thenReturn("Z")
                .thenCallRealMethod();

            assertEquals("Z", RandomStringUtils.random(1, "ABC")); // Passed
            assertNotEquals("Z", RandomStringUtils.random(1, "ABC")); // ClassCastException

            /*
            java.lang.ClassCastException: class [C cannot be cast to class java.lang.Number ([C and java.lang.Number are in module java.base of loader 'bootstrap')
	            at java.base/sun.invoke.util.ValueConversions.primitiveConversion(ValueConversions.java:247)
	            at java.base/sun.invoke.util.ValueConversions.unboxCharacter(ValueConversions.java:117)
	            at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:728)
	            at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments(MethodHandleImpl.java:532)
	            at org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:471)
	            at org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:455)
	            at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:728)
	            at org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:452)
	            at io.github.t45k.mockstatic.AppTest.primitiveAndObjectTypeArgsStaticMethodMockingFailure(AppTest.java:57)
	            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	            at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	            at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	            at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	            at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	            at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	            at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	            at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	            at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	            at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	            at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	            at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	            at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	            at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	            at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	            at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	            at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	            at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	            at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	            at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	            at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	            at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	            at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	            at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	            at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	            at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	            at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	            at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	            at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	            at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	            at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	            at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	            at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	            at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	            at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	            at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	            at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
             */
        }
    }
}
